name: Build and Deploy 

on:
  push:
    branches:
      -main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deploy
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}" 